(ql:quickload :fossicker)

(in-package :fcku)

(configure :system :fossickerrc :reloadp t)
(add-project *config* "~/dev/lisp/local-projects/fossicker/test/6x13.project")
(add-project *config* "~/dev/lisp/local-projects/fossicker/test/test.project" nil)
(remove-project *config* "~/dev/lisp/local-projects/fossicker/test/6x13.project")
(remove-project *config* "~/dev/lisp/local-projects/fossicker/test/test.project")
(inspect (fck::projects *config*))
(unload-project "test")
(load-project "6x13")
(inspect *project-registry*)
(set-project "test")
(generate "meh/bla/test_b_p_.png")
