(require 'cl)
(add-to-list 'load-path "~/dev/lisp/dists/quicklisp/software/slime-2.14")
(require 'slime)
(slime-setup nil)
(slime-start :program "sbcl")
(slime-current-connection)
(slime-connection)
(slime-process)
(setq-local slime-buffer-package ':cl)
(slime-eval '(concatenate 'string "bla" "meh") :cl)
(slime-find-buffer-package)
(slime-current-package)
(slime-eval '(cl:concatenate 'cl:string "bla" "meh"))
(slime-eval-async '(cl:concatenate 'cl:string "bla" "meh"))
(slime-message "bla")
(slime-start)
(slime-send '(cl:concatenate 'cl:string "bla" "meh"))
;; start-swank.lisp can be loaded in lisp side to start swank server automatically.
;; slime.el has great docs for everything.
(defun slimeshowpackage ()
  (interactive)
  (message "%s" (slime-current-package)))
